// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcCXQ_98OVnYUeT_AqkvnJhIz_IjakWF8',
    appId: '1:1004807216627:web:385beeb66234badd09c686',
    messagingSenderId: '1004807216627',
    projectId: 'domedome',
    authDomain: 'domedome.firebaseapp.com',
    storageBucket: 'domedome.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNmxpUlSnn4s4Y92oOcf0SYCvpdZ5XXpM',
    appId: '1:1004807216627:android:36b844eb23e984d909c686',
    messagingSenderId: '1004807216627',
    projectId: 'domedome',
    storageBucket: 'domedome.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx3HYfunASDA0ZRPMs95RTGfW-ZzCKbPs',
    appId: '1:1004807216627:ios:7448d557d710e8db09c686',
    messagingSenderId: '1004807216627',
    projectId: 'domedome',
    storageBucket: 'domedome.appspot.com',
    iosClientId: '1004807216627-etulv4fepc041i8tl5qr4d3eqtohlb42.apps.googleusercontent.com',
    iosBundleId: 'com.example.doMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx3HYfunASDA0ZRPMs95RTGfW-ZzCKbPs',
    appId: '1:1004807216627:ios:7448d557d710e8db09c686',
    messagingSenderId: '1004807216627',
    projectId: 'domedome',
    storageBucket: 'domedome.appspot.com',
    iosClientId: '1004807216627-etulv4fepc041i8tl5qr4d3eqtohlb42.apps.googleusercontent.com',
    iosBundleId: 'com.example.doMe',
  );
}
